#!/bin/sh
echo "Please Wait"
echo "Deleting Componets"
echo ""
rm  /usr/share/fonts/Plus98-Fonts
rm  /usr/share/icons/"Dangerous Creatures (256 color)"
rm  /usr/share/icons/"Inside your Computer (high color)"
rm  /usr/share/icons/"Jungle (256 color)"
rm  /usr/share/icons/"Mystery (high color)"
rm  /usr/share/icons/"BaseBall (256 color)"
rm  /usr/share/icons/"More Windows (high color)"
rm  /usr/share/icons/"Leonardo da Vinci (256 color)"
rm  /usr/share/icons/"Windows 98 (256 color)"
rm  /usr/share/icons/"Sports (256 color)"
rm  /usr/share/icons/"Nature (high color)"
rm  /usr/share/icons/"Science (256 color)"
rm  /usr/share/icons/"Underwater (high color)"
rm  /usr/share/icons/"The Golden Era (high color)"
rm  /usr/share/icons/"Travel (high color)"
rm  /usr/share/icons/"The 60's USA (256 color)"
rm  /usr/share/themes/"Dangerous Creatures (256 color)"
rm  /usr/share/themes/"Inside your Computer (high color)"
rm  /usr/share/themes/"Jungle (256 color)"
rm  /usr/share/themes/"Mystery (high color)"
rm  /usr/share/themes/"BaseBall (256 color)"
rm  /usr/share/themes/"More Windows (high color)"
rm  /usr/share/themes/"Leonardo da Vinci (256 color)"
rm  /usr/share/themes/"Windows 98 (256 color)"
rm  /usr/share/themes/"Sports (256 color)"
rm  /usr/share/themes/"Nature (high color)"
rm  /usr/share/themes/"Science (256 color)"
rm  /usr/share/themes/"Underwater (high color)"
rm  /usr/share/themes/"The Golden Era (high color)"
rm  /usr/share/themes/"Travel (high color)"
rm  /usr/share/themes/"The 60's USA (256 color)"
rm  /usr/share/sounds/"Dangerous Creatures (256 color)"
rm  /usr/share/sounds/"Inside your Computer (high color)"
rm  /usr/share/sounds/"Jungle (256 color)"
rm  /usr/share/sounds/"Mystery (high color)"
rm  /usr/share/sounds/"BaseBall (256 color)"
rm  /usr/share/sounds/"More Windows (high color)"
rm  /usr/share/sounds/"Leonardo da Vinci (256 color)"
rm  /usr/share/sounds/"Windows 98 (256 color)"
rm  /usr/share/sounds/"Sports (256 color)"
rm  /usr/share/sounds/"Nature (high color)"
rm  /usr/share/sounds/"Science (256 color)"
rm  /usr/share/sounds/"Underwater (high color)"
rm  /usr/share/sounds/"The Golden Era (high color)"
rm  /usr/share/sounds/"Travel (high color)"
rm  /usr/share/sounds/"The 60's USA (256 color)"
rm  /usr/share/gnome-background-properties/plus98.xml
rm  /usr/share/backgrounds/PLUS98-BACKGROUNDS
